# config/packages/rate_limiter.yaml
framework:
    rate_limiter:
        login_link:
            policy: 'sliding_window'
            limit: 3
            interval: '15 minutes'
        registration:
            policy: 'sliding_window'
            limit: 3
            interval: '15 minutes'
