<?php

namespace App\Repository;

/**
 * ManufacturerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManufacturerRepository extends \Doctrine\ORM\EntityRepository
{
}
