<?php

namespace App\Repository;

use App\Entity\Coaster;
use App\Entity\Notification;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Notification::class);
    }
    /**
     * @return mixed
     */
    public function markTypeAsRead(string $type)
    {
        return $this
            ->getEntityManager()
            ->createQueryBuilder()
            ->update('App:Notification n')
            ->set('n.isRead', true)
            ->where('n.type LIKE :type')
            ->setParameter('type', $type)
            ->getQuery()
            ->execute();
    }
}
