<?php

namespace App\Repository;

/**
 * RankingHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
