<?php

namespace App\Repository;

/**
 * RestraintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestraintRepository extends \Doctrine\ORM\EntityRepository
{
}
