<?php

namespace App\Repository;

use App\Entity\Top;
use App\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * TopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopRepository extends EntityRepository
{
    /**
     * Tops must have at lest 3 ranked coasters inside
     *
     * @return \Doctrine\ORM\Query
     */
    public function findAllTops()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('t')
            ->addSelect('COUNT(t.id) as HIDDEN nb')
            ->from('App:Top', 't')
            ->join('t.topCoasters', 'tc')
            ->groupBy('t.id')
            ->having('nb > 2')
            ->orderBy('t.updatedAt', 'desc')
            ->getQuery();
    }

    /**
     * @return int|mixed
     */
    public function countTops()
    {
        try {
            return $this->getEntityManager()
                ->createQueryBuilder()
                ->select('count(1)')
                ->from('App:Top', 't')
                ->where('t.main = 1')
                ->getQuery()
                ->getSingleScalarResult();
        } catch (NonUniqueResultException $e) {
            return 0;
        }
    }

    /**
     * @return \Doctrine\ORM\Query
     */
    public function findAllCustomLists()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('t')
            ->addSelect('COUNT(t.id) as HIDDEN nb')
            ->from('App:Top', 't')
            ->join('t.topCoasters', 'tc')
            ->where('t.main = 0')
            ->groupBy('t.id')
            ->having('nb > 2')
            ->orderBy('t.updatedAt', 'desc')
            ->getQuery();
    }

    /**
     * Return all lists for a user
     *
     * @param User $user
     * @return mixed
     */
    public function findAllByUser(User $user)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('t')
            ->from('App:Top', 't')
            ->where('t.user = :user')
            ->setParameter('user', $user)
            ->orderBy('t.main', 'desc')
            ->addOrderBy('t.updatedAt', 'desc')
            ->getQuery()
            ->getResult();
    }

    /**
     * @param Top $top
     * @return mixed
     * @throws NonUniqueResultException
     * @throws \Doctrine\ORM\NoResultException
     */
    public function getTopWithData(Top $top)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('t', 'tc', 'c', 'm', 'p', 'co')
            ->from('App:Top', 't')
            ->leftJoin('t.topCoasters', 'tc')
            ->leftJoin('tc.coaster', 'c')
            ->leftJoin('c.park', 'p')
            ->leftJoin('p.country', 'co')
            ->leftJoin('c.manufacturer', 'm')
            ->where('t = :top')
            ->setParameter('top', $top)
            ->getQuery()
            ->getSingleResult();
    }
}
