<?php

namespace BddBundle\Repository;

/**
 * BuiltCoasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuiltCoasterRepository extends \Doctrine\ORM\EntityRepository
{
}
