<?php

namespace BddBundle\Repository;

/**
 * BuiltCoasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuiltCoasterRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStats()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('count(1)')
            ->addSelect('sum(bc.length)')
            ->addSelect('sum(bc.inversionsNumber)')
            ->from('BddBundle:BuiltCoaster', 'bc')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
