<?php

namespace BddBundle\Repository;

/**
 * CoasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoasterRepository extends \Doctrine\ORM\EntityRepository
{
}
