<?php

namespace BddBundle\Repository;

/**
 * LaunchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaunchRepository extends \Doctrine\ORM\EntityRepository
{
}
