<?php

namespace BddBundle\Repository;

/**
 * LikeReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeReportRepository extends \Doctrine\ORM\EntityRepository
{
}
