<?php

namespace BddBundle\Repository;

/**
 * ListCoasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeCoasterRepository extends \Doctrine\ORM\EntityRepository
{
}
