<?php

namespace BddBundle\Repository;

/**
 * ListeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */
    public function countAll()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('count(1)')
            ->from('BddBundle:Liste', 'l')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findAllByUpdatedDate()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('l')
            ->addSelect('COUNT(l.id) as HIDDEN nb')
            ->from('BddBundle:Liste', 'l')
            ->join('l.listeCoasters', 'lc')
            ->groupBy('l.id')
            ->having('nb > 2')
            ->orderBy('l.updatedAt', 'desc')
            ->getQuery();
    }
}
