<?php

namespace BddBundle\Repository;

/**
 * NegativeKeyword
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NegativeKeyword extends \Doctrine\ORM\EntityRepository
{
}
