<?php

namespace BddBundle\Repository;

/**
 * ParkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParkRepository extends \Doctrine\ORM\EntityRepository
{
}
