<?php

namespace BddBundle\Repository;

/**
 * ParkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParkRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRanking()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('BddBundle:Park', 'p')
//            ->innerJoin('c.park', 'p')
//            ->innerJoin('c.builtCoaster', 'bc')
//            ->innerJoin('bc.manufacturer', 'm')
            ->where('p.rank is not null')
            ->orderBy('p.rank', 'asc')
            ->getQuery();
    }
}
