<?php

namespace BddBundle\Repository;

/**
 * PositiveKeyword
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositiveKeyword extends \Doctrine\ORM\EntityRepository
{
}
