<?php

namespace BddBundle\Repository;

/**
 * RatingCoasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingCoasterRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAll()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('count(1)')
            ->from('BddBundle:RatingCoaster', 'r')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
