<?php

namespace BddBundle\Repository;

use BddBundle\Entity\Report;
use Doctrine\ORM\EntityRepository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends EntityRepository
{
    /**
     * @param Report $report
     * @return mixed
     */
    public function addView(Report $report)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->update('BddBundle:Report', 'r')
            ->set('r.viewsNumber', $report->getViewsNumber() + 1)
            ->where('r.id = :id')
            ->setParameter('id', $report->getId())
            ->getQuery()
            ->execute();
    }
}
