<?php

namespace BddBundle\Repository;

/**
 * RiddenCoasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiddenCoasterRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAll()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('count(1)')
            ->from('BddBundle:RiddenCoaster', 'r')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function countNew(\DateTime $date)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('count(1)')
            ->from('BddBundle:RiddenCoaster', 'r')
            ->where('r.updatedAt > ?1')
            ->setParameter(1, $date)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getReviews(int $coasterId)
    {
        // add joins to avoid multiple subqueries
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('r')
            ->addSelect('p')
            ->addSelect('c')
            ->addSelect('u')
            ->from('BddBundle:RiddenCoaster', 'r')
            ->innerJoin('r.user', 'u')
            ->leftJoin('r.positiveKeywords', 'p')
            ->leftjoin('r.negativeKeywords', 'c')
            ->where('r.coaster = ?1')
            ->setParameter(1, $coasterId)
            ->orderBy('r.updatedAt', 'desc')
            ->getQuery()
            ->getResult();
    }

    public function getLastReviewsWithText($limit = 2)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('r')
//            ->addSelect('p')
//            ->addSelect('c')
            ->addSelect('u')
            ->from('BddBundle:RiddenCoaster', 'r')
            ->innerJoin('r.user', 'u')
//            ->leftJoin('r.positiveKeywords', 'p')
//            ->leftjoin('r.negativeKeywords', 'c')
            ->where('r.review is not null')
            ->orderBy('r.updatedAt', 'desc')
            ->setMaxResults(3)
            ->getQuery()
            ->getResult();
    }
}
