<?php

namespace BddBundle\Repository;

/**
 * RiddenCoasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiddenCoasterRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAll()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('count(1)')
            ->from('BddBundle:RiddenCoaster', 'r')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function countNew(\DateTime $date)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('count(1)')
            ->from('BddBundle:RiddenCoaster', 'r')
            ->where('r.updatedAt > ?1')
            ->setParameter(1, $date)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getReviews(int $coasterId, $locale = 'en')
    {
        // add joins to avoid multiple subqueries
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('r')
            ->addSelect('p')
            ->addSelect('c')
            ->addSelect('u')
            ->addSelect("CASE WHEN r.language = :locale AND r.review IS NOT NULL THEN 0 ELSE 1 END AS HIDDEN languagePriority")
            ->from('BddBundle:RiddenCoaster', 'r')
            ->innerJoin('r.user', 'u')
            ->leftJoin('r.positiveKeywords', 'p')
            ->leftjoin('r.negativeKeywords', 'c')
            ->where('r.coaster = :coasterId')
            ->orderBy('languagePriority', 'asc')
            ->addOrderBy('r.updatedAt', 'desc')
            ->setParameter('coasterId', $coasterId)
            ->setParameter('locale', $locale)
            ->getQuery()
            ->getResult();
    }

    public function getLatestReviewsByLocale($locale = 'en', $limit = 3)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('r')
            ->addSelect("CASE WHEN r.language = :locale THEN 0 ELSE 1 END AS HIDDEN languagePriority")
            ->addSelect('u')
            ->from('BddBundle:RiddenCoaster', 'r')
            ->innerJoin('r.user', 'u')
            ->where('r.review is not null')
            ->orderBy('languagePriority', 'asc')
            ->addOrderBy('r.updatedAt', 'desc')
            ->setMaxResults($limit)
            ->setParameter('locale', $locale)
            ->getQuery()
            ->getResult();
    }
}
